### ISSUE TITLE
get_service -> update_service drops some parameters

### ISSUE THREAD

**Issue by jktcp** [googleapis/python-run#95] opened 2023-04-20 17:17 UTC
#### Environment details

  - Python version: `3.11.2`
  - pip version: `23.0.1`
  - `google-cloud-run` version: `0.7.1`

#### Steps to reproduce

  1. Create Cloud Run instance with "Startup CPU boost" enabled.
  2. Run the following code sample on such instance.

#### Code example

```python
import google.cloud.run_v2
instance = 'projects/.../locations/.../services/...'
client = google.cloud.run_v2.ServicesClient()
service = client.get_service(name=instance)
service.template.revision = ''
client.update_service(service=service)
```

#### Expected result

Service is redeployed with identical settings.

#### Actual result

Service is missing at least the "Startup CPU boost" option.

I'd say it is due to [ResourceRequirements](https://github.com/googleapis/python-run/blob/main/google/cloud/run_v2/types/k8s_min.py#L173) class missing the `startupCpuBoost` parameter. In JSON it is represented as a boolean:
```
        "resources": {
          "limits": {
            "cpu": "1000m",
            "memory": "1Gi"
          },
          "startupCpuBoost": true
        },
```

**Comment by parthea** [comment] 2023-04-20 18:40
Thanks for reporting this issue. I'm going to close this issue as a duplicate of https://issuetracker.google.com/issues/279052397. Please follow the discussion in https://issuetracker.google.com/issues/279052397. Please open a new issue if you have any additional questions.

**Closed by parthea** 2023-04-20 18:40 UTC
Labels: type: bug, priority: p2, external, api: run

**Comment by jktcp** [comment] 2023-05-11 15:39
The change has been merged last week:
https://github.com/googleapis/python-run/commit/c907927b59079867825954786192954293aa6184
