### ISSUE TITLE
Invalid secret names due to parsing of alphanumeric strict requirement

### ISSUE THREAD

**Issue by kutysam** [googleapis/python-run#84] opened 2023-02-02 20:44 UTC
"Violation in UpdateServiceRequest.service.template.volumes[0].secret.items[0].path: may only have up to 255 alphanumeric characters, hyphens, and underscores."

```
secret: "censored"
items {
  path: "server-ca.pem"
  version: "latest"
}
```

`.` should be allowed too.

**Comment by parthea** [comment] 2023-02-15 16:56
Also see https://issuetracker.google.com/issues/267733153

**Comment by parthea** [comment] 2023-02-16 10:36
Thanks for reporting this issue. I'm going to close it as a duplicate of https://issuetracker.google.com/issues/267733153 which is being handled by the Google Cloud Run Team.

**Closed by parthea** 2023-02-16 10:36 UTC
Labels: status: investigating, api: run
